import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <h1>Isto vai aparecer em todas as páginas pq faz parte do layout do root</h1>
        {children}
      </body>
    </html>
  )
}
